Repository enjin/indexer, pull requests merged in 2022-12, with the labels that each got.

#125 Updates URL
  docker-compose.yml
Labels: dependencies

#129 Changes for new staging environment
  db/migrations/1670968668237-Data.js
  docker-compose.yml
  src/mappings/marketplace/events/auction_finalized.ts
  src/mappings/marketplace/events/bid_placed.ts
  src/mappings/marketplace/events/listing_created.ts
  src/mappings/multiTokens/events/collection_created.ts
  src/mappings/multiTokens/events/collection_mutated.ts
  src/mappings/multiTokens/events/frozen.ts
  src/mappings/multiTokens/events/minted.ts
  src/mappings/multiTokens/events/thawed.ts
  src/mappings/multiTokens/events/token_created.ts
  src/mappings/multiTokens/events/token_mutated.ts
  src/mappings/multiTokens/events/transferred.ts
  src/processor.ts
  src/types/generated/calls.ts
  src/types/generated/events.ts
  src/types/generated/storage.ts
  src/types/generated/v3000.ts
  src/types/generated/v5.ts
  typegen/chainSpecVersions.jsonl
  typegen/devfinityVersions.jsonl
  typegen/stagingVersions.jsonl
Labels: enhancement

#132 [PLA-495] Add tokenValues to account
  db/migrations/1671133948712-Data.js
  schema.graphql
  src/mappings/multiTokens/events/burned.ts
  src/mappings/multiTokens/events/minted.ts
  src/mappings/multiTokens/events/transferred.ts
  src/mappings/util/entities.ts
  src/model/generated/account.model.ts
Labels: enhancement

#133 [PLA-495] Fixes account error
  src/mappings/balances/processor.ts
Labels: bug

#135 [PLA-496] [PLA-497] Adds TokenMutated and CollectionMutated
  src/mappings/multiTokens/events/collection_mutated.ts
  src/mappings/multiTokens/events/index.ts
  src/mappings/multiTokens/events/token_mutated.ts
  src/processor.ts
Labels: enhancement

#136 [PLA-502] Indexer crashes when creating collection with attributes
  src/mappings/multiTokens/events/attribute_set.ts
  src/mappings/multiTokens/events/collection_created.ts
Labels: bug

#144 [PLA-519] parseMedia non array values
  src/mappings/util/metadata.ts
Labels: bug

#146 [PLA-522] Adds Squid manifest
  squid.yml
Labels: dependencies

#147 [PLA-523] Add cache to graphql queries
  Dockerfile
Labels: enhancement

#148 [PLA-523] Adds cache
  Dockerfile
Labels: bug

#152 [PLA-529] Improve docker for osx
  .env
  .env.example
  .gitignore
  Dockerfile
  docker-compose.yml
  package-lock.json
  refresh_db.sh
  src/common/consts.ts
  src/mappings/multiTokens/events/collection_mutated.ts
  src/processor.ts
Labels: enhancement
